=pypi_mirror.py= is a small script to generate a partial PyPi
mirror. It relies on =pip= to do the most difficult part of the job
(downloading a package and its dependencies).

* Why?

Because most of the time you don't need a full PyPI mirror but only
a mirror that contains the packages you use. If you want a full PyPI
mirror you should look at [[https://github.com/pypa/bandersnatch.git][bandersnatch]].

* Installation

The script does not have any external dependencies so you just have to
copy it in the location of your choice to use it.

* How to use it?

The script provides several commands to manage your mirror. To find
out which commands are available, type:

#+BEGIN_SRC sh
  pypi_mirror.py --help
#+END_SRC

Every command provides its own help message. So for example to get the
help message of the =download= command, type:

#+BEGIN_SRC sh
  pypi_mirror.py download --help
#+END_SRC

The commands that you will probably use the most are the =download=
command and the =create= command. For example to create a mirror which
contains the =aiohttp= package and its dependencies, you can type the
following:

#+BEGIN_SRC sh
  pypi_mirror.py -d downloads download requests
  pypi_mirror.py -d downloads create -m simple
#+END_SRC

The first command will create a =downloads= directory into the current
directory and use =pip= to download the =aiohttp= package and its
dependencies into the newly created directory. Then the =create=
command will create a =simple= directory into the current directory
and will build the mirror inside this newly created directory. You can
add new packages by repeating this sequence of commands.

To make your mirror available through HTTP, you can point your HTTP
server of choice to the =simple= directory. For exemple, type the
following command into the current directory:

#+BEGIN_SRC sh
  python3 -m http.server
#+END_SRC

It will start a HTTP server that will serve file from the current
directory (which should contains the =downloads= directory and the
=simple= directory). You can then install packages using your brand
new mirror using the following command:

#+BEGIN_SRC sh
  pip install -i http://127.0.0.1:8000/simple requests
#+END_SRC
